### ISSUE TITLE
Error loading data: Missing required field \'UserContext\

### ISSUE THREAD

**Issue by brampostma** [databricks-demos/dbconnect-plotly#1]
Within the flask app i get an error when the app tries to use databricks connect 2.0:

```
pyspark.errors.exceptions.connect.SparkConnectGrpcException: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Missing required field 'UserContext' in the request."
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Missing required field \'UserContext\' in the request.", grpc_status:3, created_time:"2023-05-03T11:53:35.560598357+00:00"}"
>
```

This gives me the feeling that it may be related to the authentication or authorization of the DatabricksSession object.
The databricks cli is configured correctly and works and the cluster has runtime 13.0.\

What could be wrong?

**Comment by grundprinzip** [comment]
There is a case when run in Docker that the `$USER` variable is not set causing this issue. As a workaround please export the environment variable like this in the code `os.environ["USER"] = "an"` We will fix this in the Databricks Connect connector very soon.

**Comment by brampostma** [comment]
Thanks, that seems to remove the error indeed. The Data is showing fine now in the app.
